# Generated by Django 5.1.3 on 2024-11-12 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Electricity_Bill',
            fields=[
                ('Customer_ID', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('Customer_name', models.CharField(max_length=50)),
                ('Bill_no', models.IntegerField()),
                ('Bill_amount', models.IntegerField()),
                ('Bill_date', models.DateField()),
            ],
        ),
    ]
